simulinkModel = 'myModel';
load_system(simulinkModel);
try
  codeMapObj = coder.mapping.api.get(simulinkModel);
          fprintf("" + ...
            " ========================================================\n" + ...
            " The model already had code mappings.\n" + ...
            " ========================================================\n");
catch
          fprintf("" + ...
            " ==========================================\n" + ...
            " The model does not have code mappings.\n" + ...
            " Creating new code mappings for the model.\n" + ...
            " ==========================================\n");
%   codeMapObj = coder.mapping.utils.create(simulinkModel);
end